apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophish.fullname" . }}
  labels:
    {{- include "gophish.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.port }}
    - port: {{ . }}
      targetPort: {{.}}
      protocol: TCP
      name: http-{{.}}
    {{ end }}
  selector:
    {{- include "gophish.selectorLabels" . | nindent 4 }}
