
global: []


ingressAdmin:
  enabled: true
  className: 
  annotations: #{}
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: le-stage
    #ingress.kubernetes.io/whitelist-source-range: 35.193.187.118,35.193.131.70,34.138.94.202,34.86.120.167,34.86.212.150,34.85.161.54,96.126.105.71
    # kubernetes.io/tls-acme: true
  hosts:
    - host: gophish.toolbox.tryb.co.za
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: gophish.toolbox.tryb.co.za-tls
     hosts:
       - gophish.toolbox.tryb.co.za

ingress:
  enabled: true
  className: 
  annotations: #{}
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: le-stage
    #ingress.kubernetes.io/whitelist-source-range: 35.193.187.118,35.193.131.70,34.138.94.202,34.86.120.167,34.86.212.150,34.85.161.54,96.126.105.71
    # kubernetes.io/tls-acme: true
  hosts:
    - host: test.marketingautomation.solutions
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: test.marketingautomation.solutions-tls
     hosts:
       - test.marketingautomation.solutions


         #image:

configMap:
  admin_server_listen_url: "0.0.0.0:3333"
  admin_server_use_tls: false

  admin_server_cert_path: "gophish_admin.crt"
  admin_server_key_path: "gophish_admin.key"
  phish_server_listen_url: "0.0.0.0:80"

  phish_server_use_tls: false
  phish_server_cert_path: "example.crt"
  phish_server_key_path: "example.key"

  db_name: "sqlite3"
  db_path": "gophish.db"

  migrations_prefix": "db/db_"
  contact_address: ""
  logging_filename: ""
  logging_level": ""


